---
version: '3'

include:
  - ../../addon/docker-compose.yml

services:
  azure_deployment_url:
    build: azure_deployment_mock
    environment:
      API_KEY: AZURE_MODEL_API_KEY

  test:
    build: test-addon
    environment:
      DIAL_URL: "http://core:8080"
      DIAL_API_KEY: "dial_api_key"
    depends_on:
      azure_deployment_url:
        condition: service_started
      adapter-openai:
        condition: service_started
      assistant:
        condition: service_started
      addon:
        condition: service_started
      core:
        condition: service_healthy