---
version: '3'

include:
  - ../../application/docker-compose.yml

services:
  test:
    build: test
    environment:
      DIAL_URL: "http://core:8080"
      DIAL_API_KEY: "dial_api_key"
    depends_on:
      echo:
        condition: service_started
      core:
        condition: service_healthy