services:
  adapter:
    build: .
    depends_on:
      - provider-eu
      - provider-us

  provider-eu:
    build: mock-provider
    environment:
      UPSTREAM_NAME: "provider-eu"
      EXPECTED_KEY: "eu-provider-key"

  provider-us:
    build: mock-provider
    environment:
      UPSTREAM_NAME: "provider-us"
      EXPECTED_KEY: "us-provider-key"

  core:
    image: epam/ai-dial-core:0.47.1
    environment:
      aidial.config.files: '["/opt/config/config.json"]'
      aidial.storage.overrides: '{ "jclouds.filesystem.basedir": "data" }'
      aidial.redis.singleServerConfig.address: "redis://redis:6379"
      aidial.identityProviders.test.rolePath: 'roles'
      aidial.identityProviders.test.disableJwtVerification: 'true'
      aidial.encryption.secret: 'salt'
      aidial.encryption.key: 'password'
    ports:
      - "8080:8080"
    volumes:
      - ./config.json:/opt/config/config.json
    depends_on:
      - redis

  redis:
    image: redis:7.2.4-alpine3.19
    command: >
      redis-server
      --maxmemory 256mb
      --maxmemory-policy volatile-lfu
      --save ""
      --appendonly no
