include:
  - path: ../common.yml
    env_file: ./.env

services:
  ollama:
    image: ollama/ollama:0.3.10
    volumes:
      - ./.ollama:/root/.ollama
    ports:
      - "11434:11434"

  ollama-setup:
    depends_on:
      ollama:
        condition: service_started
    image: alpine:3.20.3
    environment:
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_ENABLED=${OLLAMA_ENABLED:-1}
      - OLLAMA_MODEL=${OLLAMA_MODEL:-llama3:8b-instruct-q2_K}
      - OLLAMA_MODEL_ALIAS=${OLLAMA_MODEL_ALIAS:-llama3:8b}
    volumes:
      - ./ollama_setup.sh:/setup.sh
    command: sh /setup.sh
    healthcheck:
      test: ["CMD", "test", "-f", "/healthy"]
      interval: 10s
      start_period: 10s
      retries: 10
