#!/usr/bin/env -S npx tsx
/**
 * sync-tracking.ts
 *
 * Idempotent script that generates or updates docs-planning/tracking.json
 * by reconciling:
 *   1. sidebars.js NEW section (actual sidebar state)
 *   2. docs-planning/recommended-site-structure.md (target state)
 *   3. OLD docs filesystem (source pages for mapping)
 *   4. Existing tracking.json (preserved — never modified)
 *
 * Behavior: APPEND-ONLY. Existing records are never modified.
 * New stub records are created for untracked pages.
 *
 * Usage:
 *   npx tsx scripts/sync-tracking.ts
 *   npx tsx scripts/sync-tracking.ts --dry-run   # report only, don't write
 */

import * as fs from "node:fs";
import * as path from "node:path";
import matter from "gray-matter";

import {
    type TrackingRecord,
    type TrackingFile,
    type PageType,
    type AnyDocStatus,
    type MappingType,
    type PageInfo,
    REPO_ROOT,
    TRACKING_PATH,
    STRUCTURE_PATH,
    readTrackingFile,
    writeTrackingFile,
    readStructureOrder,
    sortByStructure,
    validateAllRecords,
    printIssues,
} from "./tracking-shared";

// ---------- Config ----------

const DOCS_ROOT = path.join(REPO_ROOT, "docs");        // OLD docs instance
const V2_ROOT = path.join(REPO_ROOT, "docs_v2");       // NEW docs instance
const SIDEBARS_PATH = path.join(REPO_ROOT, "sidebars.js");        // OLD sidebar
const V2_SIDEBARS_PATH = path.join(REPO_ROOT, "sidebars-v2.js");  // NEW sidebar
const PROGRESS_REL_PATH = "docs_v2/progress.md";
/** Autogenerated sidebar dirs holding generated (non-authored) content — skip in tracking.
 *  Relative to the NEW instance root (docs_v2). */
const IGNORED_AUTOGEN_DIRS = ["reference/changelog"];
const dryRun = process.argv.includes("--dry-run");

// ---------- Types ----------

interface SidebarDoc {
    id: string;
    label: string;
    menuPath: string;
    section: "OLD" | "NEW";
}

interface OldPageInfo {
    docId: string;
    filePath: string;
    title: string;
    menuPath: string;
}

interface StructureEntry {
    title: string;
    pageType: PageType;
    sectionPath: string;
    isNew: boolean;
    sourceAnnotation: string;
}

// ---------- Sidebar parser ----------

async function parseSidebars(): Promise<SidebarDoc[]> {
    const docs: SidebarDoc[] = [];

    function walk(items: unknown[], breadcrumb: string[], section: "OLD" | "NEW", root: string): void {
        for (const item of items) {
            if (typeof item === "string") {
                docs.push({
                    id: item,
                    label: item.split("/").pop() ?? item,
                    menuPath: [...breadcrumb, item.split("/").pop() ?? item].join(" > "),
                    section,
                });
                continue;
            }
            if (!item || typeof item !== "object") continue;
            const obj = item as Record<string, unknown>;

            if (obj.type === "doc" && typeof obj.id === "string") {
                const label = (typeof obj.label === "string" ? obj.label : obj.id.split("/").pop()) ?? obj.id;
                docs.push({
                    id: obj.id,
                    label,
                    menuPath: [...breadcrumb, label].join(" > "),
                    section,
                });
            } else if (obj.type === "category" && typeof obj.label === "string") {
                if (Array.isArray(obj.items)) {
                    walk(obj.items, [...breadcrumb, obj.label], section, root);
                }
            } else if (obj.type === "autogenerated" && typeof obj.dirName === "string") {
                // Generated content (e.g. the Changelog, built by scripts/build-changelog.ts)
                // is not authored docs and is excluded from progress tracking.
                if (IGNORED_AUTOGEN_DIRS.some((d) => obj.dirName === d || (obj.dirName as string).startsWith(d + "/"))) {
                    continue;
                }
                const dir = path.join(root, obj.dirName);
                if (fs.existsSync(dir)) {
                    for (const file of walkDir(dir)) {
                        const rel = path.relative(root, file);
                        const id = rel.replace(/\.mdx?$/, "").replace(/\d+\./g, "");
                        const label = path.basename(file, path.extname(file)).replace(/^\d+\./, "");
                        docs.push({
                            id,
                            label,
                            menuPath: [...breadcrumb, label].join(" > "),
                            section,
                        });
                    }
                }
            }
            // Skip type: 'link' (external links)
        }
    }

    // OLD instance: sidebars.js (CustomSideBar holds a single "OLD" top category)
    const oldMod = await import(SIDEBARS_PATH);
    const oldSidebar = (oldMod.default ?? oldMod).CustomSideBar;
    if (!Array.isArray(oldSidebar)) {
        throw new Error("Could not find CustomSideBar array in sidebars.js");
    }
    walk(oldSidebar, [], "OLD", DOCS_ROOT);

    // NEW instance: sidebars-v2.js (v2Sidebar), ids relative to docs_v2/
    const v2Mod = await import(V2_SIDEBARS_PATH);
    const v2Sidebar = (v2Mod.default ?? v2Mod).v2Sidebar;
    if (!Array.isArray(v2Sidebar)) {
        throw new Error("Could not find v2Sidebar array in sidebars-v2.js");
    }
    walk(v2Sidebar, ["NEW"], "NEW", V2_ROOT);

    return docs;
}

function walkDir(dir: string): string[] {
    const results: string[] = [];
    for (const entry of fs.readdirSync(dir)) {
        const full = path.join(dir, entry);
        if (fs.statSync(full).isDirectory()) {
            results.push(...walkDir(full));
        } else if (/\.mdx?$/.test(entry)) {
            results.push(full);
        }
    }
    return results;
}

// ---------- Doc ID to file path resolver ----------

function resolveDocIdToFilePath(docId: string, root: string): string | null {
    // docId like "platform/architecture-and-concepts/vision"
    // -> file like "docs/platform/0.architecture-and-concepts/0.vision.md"
    // (root selects the instance: DOCS_ROOT for OLD, V2_ROOT for NEW)
    const segments = docId.split("/");
    let currentDir = root;

    for (let i = 0; i < segments.length; i++) {
        const seg = segments[i];
        const isLast = i === segments.length - 1;

        if (!fs.existsSync(currentDir)) return null;
        const entries = fs.readdirSync(currentDir);

        if (isLast) {
            // Find file matching seg (with optional numeric prefix and .md/.mdx extension)
            const pattern = new RegExp(`^(\\d+\\.)?${escapeRegex(seg)}(\\.mdx?)$`);
            const match = entries.find((e) => pattern.test(e));
            if (match) {
                return path.relative(REPO_ROOT, path.join(currentDir, match));
            }
            // Also check if it's a directory with an index file
            const dirMatch = entries.find((e) => {
                const stripped = e.replace(/^\d+\./, "");
                return stripped === seg && fs.statSync(path.join(currentDir, e)).isDirectory();
            });
            if (dirMatch) {
                const indexFiles = fs.readdirSync(path.join(currentDir, dirMatch));
                const idx = indexFiles.find((f) => /^(\d+\.)?index\.mdx?$/.test(f));
                if (idx) {
                    return path.relative(REPO_ROOT, path.join(currentDir, dirMatch, idx));
                }
            }
            return null;
        }

        // Find directory matching segment (with optional numeric prefix)
        const dirPattern = new RegExp(`^(\\d+\\.)?${escapeRegex(seg)}$`);
        const dirMatch = entries.find(
            (e) => dirPattern.test(e) && fs.statSync(path.join(currentDir, e)).isDirectory(),
        );
        if (dirMatch) {
            currentDir = path.join(currentDir, dirMatch);
        } else {
            // Try exact match for non-prefixed directories
            if (entries.includes(seg) && fs.statSync(path.join(currentDir, seg)).isDirectory()) {
                currentDir = path.join(currentDir, seg);
            } else {
                return null;
            }
        }
    }
    return null;
}

function escapeRegex(s: string): string {
    return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// ---------- OLD page index ----------

function buildOldPageIndex(oldDocs: SidebarDoc[]): Map<string, OldPageInfo> {
    const index = new Map<string, OldPageInfo>();
    for (const doc of oldDocs) {
        const filePath = resolveDocIdToFilePath(doc.id, DOCS_ROOT);
        if (!filePath) continue;
        const fullPath = path.join(REPO_ROOT, filePath);
        let title = doc.label;
        try {
            const raw = fs.readFileSync(fullPath, "utf-8");
            const { data, content } = matter(raw);
            if (typeof data.title === "string") {
                title = data.title;
            } else {
                const h1 = content.match(/^#\s+(.+)$/m);
                if (h1) title = h1[1].trim();
            }
        } catch {
            // Use sidebar label as fallback
        }
        index.set(doc.id, {
            docId: doc.id,
            filePath,
            title,
            menuPath: doc.menuPath,
        });
    }
    return index;
}

// ---------- Recommended structure parser ----------

function parseRecommendedStructure(): StructureEntry[] {
    if (!fs.existsSync(STRUCTURE_PATH)) return [];
    const md = fs.readFileSync(STRUCTURE_PATH, "utf-8");
    const entries: StructureEntry[] = [];
    const lines = md.split(/\r?\n/);

    let inContent = false;
    const sectionStack: string[] = [];
    let lastHeadingLevel = 0;

    for (const line of lines) {
        if (!inContent && /^###\s+\d/.test(line)) inContent = true;
        if (inContent && /^##\s+Current pages/i.test(line)) break;
        if (!inContent) continue;

        // Track heading nesting for section path
        const heading = line.match(/^(#{2,6})\s+(.+?)\s*$/);
        if (heading) {
            const level = heading[1].length;
            const title = heading[2]
                .replace(/^\d+\\?\.\s*/, "")
                .replace(/\*\*🆕\*\*/g, "")
                .replace(/`\[[^\]]+\]`/g, "")
                .replace(/←.*$/, "")
                .replace(/\*[^*]*\*/g, "")
                .replace(/`/g, "")
                .replace(/\s*—\s*$/, "")
                .trim();

            while (sectionStack.length > 0 && lastHeadingLevel >= level) {
                sectionStack.pop();
                lastHeadingLevel--;
            }
            sectionStack.push(title);
            lastHeadingLevel = level;
            continue;
        }

        // List items are the actual page entries
        const li = line.match(/^\s*[*-]\s+(.+?)\s*$/);
        if (!li) continue;

        const rawTitle = li[1];
        const isNew = rawTitle.includes("🆕");

        // Extract page type from [Tutorial], [How-to], etc.
        const typeMatch = rawTitle.match(/`?\[?(Tutorial|How-to|Reference|Explanation|Landing)\]?`?/i);
        let pageType: PageType = "unknown";
        if (typeMatch) {
            const t = typeMatch[1].toLowerCase();
            if (t === "tutorial") pageType = "tutorial";
            else if (t === "how-to") pageType = "how-to";
            else if (t === "reference") pageType = "reference";
            else if (t === "explanation" || t === "landing") pageType = "explanation";
        }

        // Extract source annotation
        const sourceMatch = rawTitle.match(/←\s*(.+?)(?:\s*$)/);
        const sourceAnnotation = sourceMatch ? sourceMatch[1].replace(/\*/g, "").trim() : "";

        // Clean title
        const title = rawTitle
            .replace(/`\[[^\]]+\]`/g, "")
            .replace(/\*\*🆕\*\*/g, "")
            .replace(/←.*$/, "")
            .replace(/\*[^*]*\*/g, "")
            .replace(/`/g, "")
            .replace(/\s*—\s*$/, "")
            .trim();

        if (!title) continue;

        entries.push({
            title,
            pageType,
            sectionPath: sectionStack.join(" > "),
            isNew,
            sourceAnnotation,
        });
    }
    return entries;
}

// ---------- Mapping heuristics ----------

function normalizeForMatch(s: string): string {
    return s.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
}

const STOP_WORDS = new Set([
    "the", "and", "with", "for", "from", "into", "about", "how", "what",
    "are", "create", "build", "using", "guide", "overview", "deploy",
    "configure", "setup", "install", "tutorial", "example", "examples",
]);

function findBestOldMatch(
    newTitle: string,
    oldIndex: Map<string, OldPageInfo>,
): { match: OldPageInfo; confidence: "HIGH" | "MEDIUM" } | null {
    const normalized = normalizeForMatch(newTitle);

    // Exact title match
    for (const info of oldIndex.values()) {
        if (normalizeForMatch(info.title) === normalized) {
            return { match: info, confidence: "HIGH" };
        }
    }

    // Partial match: require significant word overlap (not stop words)
    const words = normalized
        .split(/\s+/)
        .filter((w) => w.length > 3 && !STOP_WORDS.has(w));
    if (words.length < 2) return null;

    let bestMatch: OldPageInfo | null = null;
    let bestScore = 0;

    for (const info of oldIndex.values()) {
        const target = normalizeForMatch(info.title);
        const matchCount = words.filter((w) => target.includes(w)).length;
        const score = matchCount / words.length;
        if (score >= 0.8 && matchCount >= 2 && score > bestScore) {
            bestScore = score;
            bestMatch = info;
        }
    }

    if (bestMatch) {
        return { match: bestMatch, confidence: "MEDIUM" };
    }
    return null;
}

function resolveSourceAnnotation(
    annotation: string,
    oldIndex: Map<string, OldPageInfo>,
): OldPageInfo | null {
    if (!annotation) return null;

    // Normalize: "currently: Platform > Core > Interceptors"
    const cleaned = annotation
        .replace(/^currently:\s*/i, "")
        .replace(/\(.*\)/, "")
        .trim();

    // Try matching against menuPath
    const normalizedCleaned = normalizeForMatch(cleaned);
    for (const info of oldIndex.values()) {
        const normalizedMenu = normalizeForMatch(info.menuPath);
        if (normalizedMenu.includes(normalizedCleaned) || normalizedCleaned.includes(normalizedMenu)) {
            return info;
        }
    }

    // Try matching key words from the annotation against doc IDs
    const keywords = normalizedCleaned.split(/\s+/).filter((w) => w.length > 2);
    for (const info of oldIndex.values()) {
        const normalizedId = normalizeForMatch(info.docId);
        const matchCount = keywords.filter((k) => normalizedId.includes(k)).length;
        if (matchCount >= keywords.length * 0.5 && matchCount >= 2) {
            return info;
        }
    }

    return null;
}

// ---------- Frontmatter reader ----------

function readPageType(filePath: string): PageType {
    const fullPath = path.join(REPO_ROOT, filePath);
    try {
        const raw = fs.readFileSync(fullPath, "utf-8");
        const { data } = matter(raw);
        const t = String(data.type ?? "").toLowerCase();
        if (t === "tutorial") return "tutorial";
        if (t === "how-to") return "how-to";
        if (t === "reference") return "reference";
        if (t === "explanation") return "explanation";
    } catch {
        // Fall through
    }
    return "unknown";
}

// ---------- Status helper ----------

function defaultStatus(pageType: PageType, hasFile: boolean): AnyDocStatus {
    if (!hasFile) return "planned";
    if (pageType === "tutorial") return "waiting-for-test";
    return "waiting-for-review";
}

// ---------- Main ----------

async function main() {
    console.log("🔄 Syncing tracking.json...\n");

    // 1. Parse sidebar
    const allDocs = await parseSidebars();
    const oldDocs = allDocs.filter((d) => d.section === "OLD");
    const newDocs = allDocs.filter((d) => d.section === "NEW");
    console.log(`  Sidebar: ${oldDocs.length} OLD docs, ${newDocs.length} NEW docs`);

    // 2. Build OLD page index
    const oldIndex = buildOldPageIndex(oldDocs);
    console.log(`  OLD pages indexed: ${oldIndex.size}`);

    // 3. Parse recommended structure
    const structureEntries = parseRecommendedStructure();
    console.log(`  Structure entries: ${structureEntries.length}`);

    // 4. Load existing tracking
    const file = readTrackingFile();
    const existingRecords = file.records;
    const existingPaths = new Set(
        existingRecords.map((r) => r.targetPage?.filePath?.trim()).filter(Boolean),
    );
    console.log(`  Existing records: ${existingRecords.length}`);

    // 5. Detect untracked sidebar pages
    const newRecords: TrackingRecord[] = [];
    let addedFromSidebar = 0;
    let addedFromStructure = 0;

    for (const doc of newDocs) {
        const filePath = resolveDocIdToFilePath(doc.id, V2_ROOT);
        if (!filePath) {
            console.warn(`  ⚠ Could not resolve doc ID: ${doc.id}`);
            continue;
        }
        if (filePath === PROGRESS_REL_PATH) continue;
        if (existingPaths.has(filePath)) continue;

        const pageType = readPageType(filePath);
        const status = defaultStatus(pageType, true);

        // Try to find mapping
        const titleMatch = findBestOldMatch(doc.label, oldIndex);
        let sourcePages: PageInfo[] = [];
        let mappingType: MappingType = "new";
        let notes = "";

        if (titleMatch) {
            sourcePages = [{
                pageType: titleMatch.match.docId.includes("tutorial") ? "how-to" as PageType : "explanation" as PageType,
                menuPath: titleMatch.match.menuPath,
                filePath: titleMatch.match.filePath,
            }];
            mappingType = "1-to-1";
            notes = `AUTO-MAPPED (${titleMatch.confidence}): from ${titleMatch.match.filePath}`;
        } else {
            notes = "NEEDS_MAPPING: no matching OLD page found. Set sourcePages and mappingType manually.";
        }

        newRecords.push({
            targetPage: {
                pageType,
                menuPath: doc.menuPath,
                filePath,
            },
            sourcePages,
            status,
            mappingType,
            notes,
        });
        addedFromSidebar++;
    }

    // 6. Detect untracked recommended-structure entries
    // (pages that are planned but don't exist in the sidebar yet)
    const trackedPaths = new Set([
        ...existingPaths,
        ...newRecords.map((r) => r.targetPage.filePath),
    ]);
    // Build a slug set from all tracked file paths for fuzzy dedup
    const trackedSlugs = new Set<string>();
    for (const fp of trackedPaths) {
        if (!fp) continue;
        // Extract the last meaningful segment (filename without extension and numeric prefix)
        const base = path.basename(fp, path.extname(fp)).replace(/^\d+\./, "");
        trackedSlugs.add(slugify(base));
    }

    for (const entry of structureEntries) {
        // Skip section-level entries that are just category labels
        if (entry.pageType === "unknown" && !entry.isNew && !entry.sourceAnnotation) continue;

        // Build proposed file path based on section
        const proposedPath = buildProposedPath(entry);
        if (trackedPaths.has(proposedPath)) continue;

        // Check if the slug already exists (catches cases where the path format differs)
        const entrySlug = slugify(entry.title);
        if (entrySlug.length > 5 && trackedSlugs.has(entrySlug)) continue;

        // Try to resolve source annotation
        let sourcePages: PageInfo[] = [];
        let mappingType: MappingType = entry.isNew ? "new" : "1-to-1";
        let notes = "";

        if (entry.sourceAnnotation) {
            const resolved = resolveSourceAnnotation(entry.sourceAnnotation, oldIndex);
            if (resolved) {
                sourcePages = [{
                    pageType: "unknown",
                    menuPath: resolved.menuPath,
                    filePath: resolved.filePath,
                }];
                notes = `From recommended structure: ${entry.sourceAnnotation}`;

                // Check if annotation mentions multiple sources
                if (/TWO|merge|fragmented|absorb/i.test(entry.sourceAnnotation)) {
                    mappingType = "merged";
                    notes = `NEEDS_REVIEW: annotation suggests merge. ${entry.sourceAnnotation}`;
                }
            } else {
                notes = `NEEDS_MAPPING: could not resolve annotation "${entry.sourceAnnotation}"`;
                mappingType = entry.isNew ? "new" : "1-to-1";
                if (!entry.isNew) sourcePages = [];
            }
        } else if (entry.isNew) {
            notes = "New page per recommended structure.";
        } else {
            notes = "NEEDS_MAPPING: no source annotation in recommended structure.";
        }

        // Fix cardinality: "1-to-1" needs exactly 1 source, "merged" needs 2+
        if (mappingType === "1-to-1" && sourcePages.length !== 1) {
            mappingType = sourcePages.length === 0 ? "new" : "merged";
        }
        if (mappingType === "merged" && sourcePages.length < 2) {
            mappingType = sourcePages.length === 1 ? "1-to-1" : "new";
        }

        const pageType = entry.pageType;
        const status = defaultStatus(pageType, false);

        newRecords.push({
            targetPage: {
                pageType,
                menuPath: entry.sectionPath ? `NEW > ${entry.sectionPath} > ${entry.title}` : `NEW > ${entry.title}`,
                filePath: proposedPath,
            },
            sourcePages,
            status,
            mappingType,
            notes,
        });
        addedFromStructure++;
        trackedPaths.add(proposedPath);
        trackedSlugs.add(slugify(entry.title));
    }

    // 7. Report warnings for existing records with missing files
    let warnings = 0;
    for (const r of existingRecords) {
        const fp = r.targetPage?.filePath?.trim();
        if (!fp || r.mappingType === "deleted" || r.status === "planned") continue;
        const fullPath = path.join(REPO_ROOT, fp);
        if (!fs.existsSync(fullPath)) {
            console.warn(`  ⚠ File missing for tracked record: ${fp}`);
            warnings++;
        }
    }

    // 8. Merge, sort, validate, write
    const allRecords = [...existingRecords, ...newRecords];
    const structureOrder = readStructureOrder();
    const sorted = sortByStructure(allRecords, structureOrder);

    const issues = validateAllRecords(sorted);
    const errors = issues.filter((i) => i.level === "error");
    if (errors.length > 0) {
        console.error("\n✖ Validation errors in generated records:");
        printIssues(errors);
    }

    console.log(`\n  Summary:`);
    console.log(`    Existing records: ${existingRecords.length} (unchanged)`);
    console.log(`    Added from sidebar: ${addedFromSidebar}`);
    console.log(`    Added from structure: ${addedFromStructure}`);
    console.log(`    Total records: ${sorted.length}`);
    console.log(`    Warnings: ${warnings}`);
    console.log(`    Validation errors: ${errors.length}`);

    if (dryRun) {
        console.log("\n  --dry-run: no changes written.");
        process.exit(errors.length > 0 ? 1 : 0);
    }

    file.records = sorted;
    writeTrackingFile(file);
    console.log(`\n✔ Wrote ${TRACKING_PATH} (${sorted.length} records).`);
    process.exit(errors.length > 0 ? 1 : 0);
}

// ---------- Path builder ----------

function buildProposedPath(entry: StructureEntry): string {
    // Convert section path + title into a proposed file path
    const sectionPath = entry.sectionPath.toLowerCase();
    const title = entry.title.toLowerCase();

    // Map top-level sections to directory paths
    if (sectionPath.includes("home")) return `docs_v2/home/${slugify(title)}.md`;
    if (sectionPath.includes("understand dial")) return `docs_v2/understand-dial/${slugify(title)}.md`;
    if (sectionPath.includes("building with dial")) return `docs_v2/building-with-dial/${subPath(sectionPath, "building with dial")}/${slugify(title)}.md`;
    if (sectionPath.includes("operating dial")) return `docs_v2/operating-dial/${subPath(sectionPath, "operating dial")}/${slugify(title)}.md`;
    if (sectionPath.includes("administering dial")) return `docs_v2/administering-dial/${slugify(title)}.md`;
    if (sectionPath.includes("chat user guide")) return `docs_v2/chat-user-guide/${slugify(title)}.md`;
    if (sectionPath.includes("reference")) return `docs_v2/reference/${slugify(title)}.md`;
    if (sectionPath.includes("use cases")) return `docs_v2/use-cases/${slugify(title)}.md`;
    if (sectionPath.includes("demos")) return `docs_v2/demos/${slugify(title)}.md`;

    return `docs_v2/${slugify(title)}.md`;
}

function subPath(sectionPath: string, prefix: string): string {
    const remainder = sectionPath
        .toLowerCase()
        .replace(new RegExp(`.*${escapeRegex(prefix)}\\s*>?\\s*`), "")
        .trim();
    if (!remainder) return "";
    return remainder
        .split(/\s*>\s*/)
        .map(slugify)
        .join("/");
}

function slugify(s: string): string {
    return s
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-+|-+$/g, "");
}

main().catch((e) => {
    console.error(`✖ ${(e as Error).message}`);
    process.exit(1);
});
