name: Deploy development

on:
  push:
    branches: [feature/doc_improvements]

jobs:
  gitlab-dev-deploy:
    uses: epam/ai-dial-ci/.github/workflows/deploy-development.yml@4.6.0
    with:
      gitlab-project-id: "3381"
    secrets:
      DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
      DEPLOY_ACCESS_TOKEN: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
      DEPLOY_TRIGGER_TOKEN: ${{ secrets.DEPLOY_TRIGGER_TOKEN }}